#ifndef __JHEAPS_CAPI_TYPES
#define __JHEAPS_CAPI_TYPES

typedef enum {
    STATUS_SUCCESS = 0, 
    STATUS_ERROR,
    STATUS_ILLEGAL_ARGUMENT,
    STATUS_UNSUPPORTED_OPERATION,
    STATUS_INDEX_OUT_OF_BOUNDS,
    STATUS_NO_SUCH_ELEMENT,
    STATUS_NULL_POINTER,
    STATUS_CLASS_CAST,
    STATUS_IO_ERROR,
} status_t;

typedef enum {
    HEAP_TYPE_PAIRING = 0,
    HEAP_TYPE_RANKPAIRING,
    HEAP_TYPE_FIBONACCI,
} heap_type_t;

#endif
