name: Build project

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest - MSVC",
            os: windows-latest,
            cc: "cl",
            cxx: "cl",
            gu: "gu.cmd"
          }
        - {
            name: "Ubuntu Latest - GCC",
            os: ubuntu-latest, 
            cc: "gcc-9",
            cxx: "g++-9",
            gu: "gu"
          }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master        
    - name: Setup GraalVM
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
        arch: 'amd64'        
    - name: Install native-image component
      run: |
        ${{ matrix.config.gu }} install native-image
    - name: Set Windows ENV
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt install build-essential zlib1g-dev g++ gcc
    - name: CMake Configure 
      run: cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
    - name: CMake Build
      run: cmake --build build
    - name: Run Tests
      run: make -C build test

