name: Build project

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        gu-binary: [gu, gu.cmd]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: windows-latest
            gu-binary: gu
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup GraalVM
      id: setup-graalvm
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm: '21.0.0.2'
        java: 'java8'
        arch: 'amd64'        
    - name: Install native-image component
      run: |
        ${{ matrix.gu-binary }} install native-image
